import Image from 'next/image'
import medavatar from '../public/dev-ed-wave.png'
import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube} from 'react-icons/ai'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Saaou Mohamed Portfolio</title>
        <meta name='description' content='Generated by me'/>
        <link rel="icon" href="./favicon.ico" />
      </Head>
      {/* className="flex min-h-screen flex-col items-center justify-between p-24" */}
      <main className='bg-white px-10'>
        <section className= 'min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons'>developped_by_med</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill className='cursor-pointer text-xl'/>
              </li>
              <li> <a className='bg-gradient-to-r from-cyan-500 to-lime-700 text-white py-2 px-4 rounded-md ml-6' href="#">Resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-5 bg-clip-text text-transparent bg-gradient-to-r from-teal-500 to-lime-600 font-extrabold'>SAAOU Mohamed</h2>
            <h3 className='text-2xl py-2 font-bold bg-clip-text text-transparent bg-gradient-to-l from-cyan-600 to-pink-800'>Data Scientist/Analyst & Developer</h3>
            <p className='flex mx-auto text-md text-justify justify-center py-5 text-gray-800'>
              Accurate Data Scientist proficient in using data to drive business decisions and solve complex problems. 
              Collect, process, and analyze large data sets, build and deploy machine learning models, design and maintain efficient data systems. 
              Working closely with stakeholders to understand their business needs and apply data-driven solutions to meet those needs. 
              Communicate the findings and insights to non-technical stakeholders and support the deployment of their models into production.
            </p>
          </div>
          <div className='text-3xl justify-center flex gap-10 py-5 text-gray-600'>
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          <div className="relative mx-auto my-10 bg-gradient-to-b from-teal-600 to-emerald-100 rounded-full w-60 h-60 overflow-hidden">
            <Image src={medavatar} alt={''} layout='fill' objectFit='cover' ></Image>
          </div>
        </section>
      </main>
    </div>
  );
}
